[package]
name = "ecksell-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.16.7"
gtk = "^0.16.0"
relm = "^0.24.0"
relm-derive = "^0.24.0"
thiserror = "1.0.38"
